Application.put_env(:riff_installer, :start_server, true)
Application.put_env(:riff_installer, :open_browser, false)
Application.put_env(:riff_installer, :port, 0)
{:ok, _} = Application.ensure_all_started(:riff_installer)
url = Riff.Installer.Session.endpoint()
{:ok, response} = Finch.build(:get, url) |> Finch.request(Riff.Installer.HTTP)
true = response.status == 200 and String.contains?(response.body, "riff-installer-token")
IO.puts("Application boot and actual loopback GUI passed.")
Application.stop(:riff_installer)
