import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { once } from "node:events";
import { mkdirSync, readFileSync } from "node:fs";
import { chromium } from "playwright";

const server = spawn(process.env.RIFF_PYTHON || "python3", ["-u", "tests/review_browser_server.py"]);
let diagnostics = "";
server.stderr.on("data", (chunk) => diagnostics += chunk);
const fixture = await new Promise((resolve, reject) => {
  let output = "";
  server.stdout.on("data", (chunk) => { output += chunk; if (output.includes("\n")) resolve(JSON.parse(output.split("\n")[0])); });
  server.once("exit", (code) => reject(new Error(`Fixture exited ${code}: ${diagnostics}`)));
});
const browser = await chromium.launch({ headless: true, executablePath: process.env.RIFF_BROWSER_EXECUTABLE });
const page = await browser.newPage({ viewport: { width: 1365, height: 1000 }, reducedMotion: "reduce" });
const errors = [];
page.on("pageerror", (error) => errors.push(error.message));
const check = (name) => console.log("PASS " + name);
mkdirSync("test-results", { recursive: true });
try {
  await page.goto(fixture.url);
  await page.locator("#play:not([disabled])").waitFor();
  assert.equal(await page.locator("html").getAttribute("data-theme"), "dark");
  assert.equal(await page.locator(".brand-i img").getAttribute("src"), "/flip-face.svg");
  await page.getByLabel("Switch color theme", { exact: true }).click();
  await page.reload();
  assert.equal(await page.locator("html").getAttribute("data-theme"), "light");
  await page.getByLabel("Switch color theme", { exact: true }).click();
  check("Riff mark, Flip theme, and persistent light/dark choice");
  await page.locator(".creative-controls > summary").click();
  await page.locator(".refinement-controls > summary").click();
  await page.locator("#control-semantic_top_p").fill("0.8");
  await page.reload();
  await page.locator(".creative-controls > summary").click();
  await page.locator(".refinement-controls > summary").click();
  assert.equal(await page.locator("#control-semantic_top_p").inputValue(), "0.8");
  await page.locator("#reset-refinement").click();
  assert.equal(await page.locator("#control-semantic_top_p").inputValue(), "");
  check("Fine tuning persists and resets to model defaults");
  await page.locator("#score-open").click();
  await page.locator("#new-score").click();
  assert(await page.locator("#score-notation svg").count());
  await page.locator("#score-tempo").fill("120");
  await page.locator("#apply-score-header").click();
  assert((await page.locator("#abc").inputValue()).includes("Q:1/4=120"));
  const before = await page.locator("#score-source").inputValue();
  await page.locator("#transpose-up").click();
  assert.notEqual(await page.locator("#score-source").inputValue(), before);
  await page.locator("#score-undo").click();
  assert.equal(await page.locator("#score-source").inputValue(), before);
  await page.locator("#score-notation .abcjs-note").first().click();
  await page.locator("#note-editor").waitFor({ state: "visible" });
  await page.locator("#note-token").fill("E2");
  await page.locator("#apply-note").click();
  assert((await page.locator("#score-source").inputValue()).includes("E2 F2"));
  await page.locator("#audition-score").click();
  await page.locator("#stop-score:not([disabled])").waitFor();
  await page.locator("#stop-score").click();
  const downloadEvent = page.waitForEvent("download");
  await page.locator("#export-midi").click();
  const midi = await downloadEvent; await midi.saveAs("test-results/composition.mid");
  assert.equal(readFileSync("test-results/composition.mid").subarray(0, 4).toString(), "MThd");
  check("Notation, tempo, transposition, note editing, tone audition, and MIDI export");
  await page.locator("#compose-score").click();
  await page.waitForFunction(() => document.querySelector("#score-status").textContent === "Score ready");
  assert((await page.locator("#abc").inputValue()).includes("A small motif"));
  await page.screenshot({ path: "test-results/composition-desktop.png" });
  await page.setViewportSize({ width: 390, height: 844 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: "test-results/composition-mobile.png" });
  await page.getByLabel("Close composition", { exact: true }).click();
  check("Score-only queue result loads into the draft and fits a narrow screen");
  await page.locator("#score-open").click();
  await page.getByText("Describe a musical change", { exact: true }).click();
  const originalScore = await page.locator("#abc").inputValue();
  await page.locator("#score-change").fill("Lift the opening phrase");
  await page.locator("#revise-score").click();
  await page.locator("#score-proposal").waitFor({ state: "visible" });
  assert.equal(await page.locator("#abc").inputValue(), originalScore);
  assert(await page.locator("#score-proposal-notation svg").count());
  await page.locator("#apply-score-proposal").click();
  assert((await page.locator("#abc").inputValue()).includes("E2 G2"));
  await page.locator("#score-undo").click();
  assert.equal(await page.locator("#abc").inputValue(), originalScore);
  await page.getByLabel("Close composition", { exact: true }).click();
  check("Plain-language score suggestions preview before applying and support undo");
  await page.getByLabel("Studio settings", { exact: true }).click();
  await page.locator("#engine-backend").selectOption("cuda");
  await page.locator("#engine-threads").fill("6");
  await page.getByRole("button", { name: "Use engine settings", exact: true }).click();
  await page.waitForFunction(() => document.querySelector("#toast").textContent === "Engine settings saved");
  const settings = await page.evaluate(async () => (await fetch("/api/system")).json());
  assert.equal(settings.engine.backend, "cuda"); assert.equal(settings.engine.threads, 6);
  await page.screenshot({ path: "test-results/studio-settings-mobile.png" });
  await page.getByLabel("Close studio settings", { exact: true }).click();
  check("Engine and update controls work without touching real settings");
  assert.deepEqual(errors, []);
} finally {
  await browser.close(); server.kill("SIGTERM"); await once(server, "exit");
}
